function [fitresult, gof] = fitTemp(x, y1)
%CREATEFIT(X,Y1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2026 12:50:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y1 );

% Set up fittype and options.
ft = fittype( 'a*(x^b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.711215780433683 0.22174673401724];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
%legend( h, 'y1 vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'latex' );
% Label axes
xlabel( '$T^{ext}$', 'Interpreter', 'latex' , fontsize=15);
ylabel( '$T^{int}$', 'Interpreter', 'latex', fontsize = 15 );
grid on


